program resisting_the_solace
  implicit none

  print *, '<!DOCTYPE html>'
  print *, '<html lang="en">'
  print *, '<head>'
  print *, '    <meta charset="UTF-8">'
  print *, '    <meta name="viewport" content="width=device-width, initial-scale=1.0">'
  print *, '    <title>Resisting the Solace | Official Website</title>'
  print *, '    <style>'
  print *, '        * { box-sizing: border-box; }'
  print *, ''
  print *, '        body, html {'
  print *, '            margin: 0; padding: 0; height: 100%;'
  print *, '            background: #000; color: #ffffff;'
  print *, '            font-family: Arial, Helvetica, sans-serif;'
  print *, '            overflow-x: hidden;'
  print *, '        }'
  print *, ''
  print *, '        /* DYNAMIC BACKGROUND */'
  print *, '        .bg-layer {'
  print *, '            position: fixed; top: 0; left: 0; width: 100%; height: 100%;'
  print *, '            background: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.9)), url(''unnamed (6).png'');'
  print *, '            background-size: cover; background-position: center;'
  print *, '            z-index: -2;'
  print *, '        }'
  print *, ''
  print *, '        .stars {'
  print *, '            position: fixed; top: 0; left: 0; width: 100%; height: 100%;'
  print *, '            z-index: -1;'
  print *, '            background: transparent;'
  print *, '            background-image: '
  print *, '                radial-gradient(1.5px 1.5px at 10% 10%, #fff, transparent),'
  print *, '                radial-gradient(1px 1px at 50% 20%, #fff, transparent),'
  print *, '                radial-gradient(2px 2px at 80% 40%, #fff, transparent),'
  print *, '                radial-gradient(1px 1px at 30% 70%, #fff, transparent),'
  print *, '                radial-gradient(1.5px 1.5px at 70% 85%, #fff, transparent);'
  print *, '            background-size: 500px 500px;'
  print *, '            animation: drift 120s linear infinite;'
  print *, '            opacity: 0.6;'
  print *, '        }'
  print *, ''
  print *, '        @keyframes drift {'
  print *, '            from { transform: translateY(0); }'
  print *, '            to { transform: translateY(-500px); }'
  print *, '        }'
  print *, ''
  print *, '        .app-container { display: flex; min-height: 100vh; }'
  print *, ''
  print *, '        nav {'
  print *, '            width: 280px;'
  print *, '            background: rgba(0, 0, 0, 0.92);'
  print *, '            border-right: 1px solid #333;'
  print *, '            padding: 50px 25px;'
  print *, '            display: flex; flex-direction: column;'
  print *, '            position: fixed; height: 100vh;'
  print *, '        }'
  print *, ''
  print *, '        .nav-brand {'
  print *, '            font-size: 1.2rem; font-weight: bold;'
  print *, '            letter-spacing: 2px; margin-bottom: 60px;'
  print *, '            color: #fff; line-height: 1.3;'
  print *, '        }'
  print *, ''
  print *, '        .brand-sub {'
  print *, '            display: block; font-size: 0.75rem; '
  print *, '            color: #fff; margin-top: 5px;'
  print *, '            text-transform: uppercase; font-weight: normal;'
  print *, '            opacity: 0.7;'
  print *, '        }'
  print *, ''
  print *, '        nav a {'
  print *, '            color: #ffffff; text-decoration: none;'
  print *, '            padding: 15px 0; margin: 5px 0;'
  print *, '            font-size: 1rem; font-weight: bold;'
  print *, '            text-transform: uppercase;'
  print *, '            cursor: pointer;'
  print *, '            border-bottom: 1px solid transparent;'
  print *, '        }'
  print *, ''
  print *, '        nav a:hover { color: #888; border-bottom: 1px solid #fff; }'
  print *, ''
  print *, '        main { margin-left: 280px; flex: 1; padding: 60px; }'
  print *, ''
  print *, '        .header-flex { display: flex; justify-content: space-between; align-items: center; margin-bottom: 60px; }'
  print *, ''
  print *, '        h1 { font-size: 2.8rem; font-weight: bold; margin: 0; text-transform: uppercase; letter-spacing: -1px; }'
  print *, ''
  print *, '        .sub-btn {'
  print *, '            background: #fff; color: #000;'
  print *, '            padding: 15px 35px; text-decoration: none;'
  print *, '            font-weight: bold; font-size: 0.9rem;'
  print *, '            text-transform: uppercase;'
  print *, '        }'
  print *, ''
  print *, '        .sub-btn:hover { background: #000; color: #fff; outline: 1px solid #fff; }'
  print *, ''
  print *, '        .grid { display: grid; grid-template-columns: 1.6fr 1fr; gap: 40px; }'
  print *, ''
  print *, '        .card {'
  print *, '            background: rgba(15, 15, 15, 0.85);'
  print *, '            backdrop-filter: blur(12px);'
  print *, '            border: 1px solid #333; padding: 40px;'
  print *, '        }'
  print *, ''
  print *, '        .section-title {'
  print *, '            font-size: 1.1rem; font-weight: bold;'
  print *, '            color: #fff; margin-bottom: 30px;'
  print *, '            border-bottom: 1px solid #fff;'
  print *, '            padding-bottom: 10px; text-transform: uppercase;'
  print *, '            letter-spacing: 2px;'
  print *, '        }'
  print *, ''
  print *, '        /* Band Member Buttons */'
  print *, '        .member-btn {'
  print *, '            display: block;'
  print *, '            text-decoration: none;'
  print *, '            color: #fff;'
  print *, '            border: 1px solid #444;'
  print *, '            padding: 20px;'
  print *, '            margin-bottom: 20px;'
  print *, '            background: rgba(255, 255, 255, 0.05);'
  print *, '            transition: 0.3s;'
  print *, '        }'
  print *, ''
  print *, '        .member-btn:hover {'
  print *, '            background: #fff;'
  print *, '            color: #000;'
  print *, '            border-color: #fff;'
  print *, '        }'
  print *, ''
  print *, '        .member-name { font-size: 1.3rem; font-weight: bold; display: block; }'
  print *, '        .member-role { font-size: 0.8rem; color: #aaa; margin-top: 5px; text-transform: uppercase; letter-spacing: 1px; }'
  print *, '        .member-btn:hover .member-role { color: #333; }'
  print *, ''
  print *, '        .big-link {'
  print *, '            display: block; color: #fff; padding: 30px;'
  print *, '            border: 1px solid #444; margin-bottom: 20px;'
  print *, '            text-decoration: none; font-size: 1.2rem; font-weight: bold;'
  print *, '            background: rgba(255,255,255,0.03);'
  print *, '            text-align: center;'
  print *, '            text-transform: uppercase;'
  print *, '        }'
  print *, ''
  print *, '        .big-link:hover { background: #fff; color: #000; }'
  print *, ''
  print *, '        .page { display: none; }'
  print *, '        .page.active { display: block; animation: fadeIn 0.5s ease; }'
  print *, ''
  print *, '        @keyframes fadeIn {'
  print *, '            from { opacity: 0; transform: translateY(10px); }'
  print *, '            to { opacity: 1; transform: translateY(0); }'
  print *, '        }'
  print *, ''
  print *, '        .about-text { line-height: 1.8; font-size: 1.1rem; color: #ececec; }'
  print *, '        .about-text p { margin-bottom: 25px; }'
  print *, ''
  print *, '        @media (max-width: 1100px) {'
  print *, '            nav { width: 100%; height: auto; position: relative; padding: 30px; }'
  print *, '            main { margin-left: 0; padding: 25px; }'
  print *, '            .grid { grid-template-columns: 1fr; }'
  print *, '            .app-container { flex-direction: column; }'
  print *, '        }'
  print *, '    </style>'
  print *, '</head>'
  print *, '<body>'
  print *, ''
  print *, '    <div class="bg-layer"></div>'
  print *, '    <div class="stars"></div>'
  print *, ''
  print *, '    <div class="app-container">'
  print *, '        <nav>'
  print *, '            <div class="nav-brand">'
  print *, '                RESISTING THE SOLACE'
  print *, '                <span class="brand-sub">Official Artist Website</span>'
  print *, '            </div>'
  print *, '            <a onclick="showPage(''dashboard'')">Home</a>'
  print *, '            <a onclick="showPage(''more-songs'')">The Gallery</a>'
  print *, '            <a onclick="showPage(''journey'')">About Us</a>'
  print *, '        </nav>'
  print *, ''
  print *, '        <main>'
  print *, '            <div id="dashboard" class="page active">'
  print *, '                <div class="header-flex">'
  print *, '                    <h1>Resisting the Solace</h1>'
  print *, '                    <a href="https://www.youtube.com/@resistingthesolace2846" class="sub-btn" target="_blank">Subscribe</a>'
  print *, '                </div>'
  print *, ''
  print *, '                <div class="grid">'
  print *, '                    <div class="card">'
  print *, '                        <div class="section-title">Our Trending Music</div>'
  print *, '                        <iframe width="100%" height="520" scrolling="no" frameborder="no" src="https://www.reverbnation.com/widget_code/html_widget/artist_6637523?widget_id=55&pwc[included_songs]=1&context_type=page_object"></iframe>'
  print *, '                    </div>'
  print *, ''
  print *, '                    <div class="card">'
  print *, '                        <div class="section-title">Band Members</div>'
  print *, '                        '
  print *, '                        <a href="https://mail.google.com/mail/?view=cm&fs=1&to=annikenprosser@gmail.com" target="_blank" class="member-btn">'
  print *, '                            <span class="member-name">Anniken Prosser</span>'
  print *, '                            <span class="member-role">Vocals / Contact</span>'
  print *, '                        </a>'
  print *, ''
  print *, '                        <a href="https://mail.google.com/mail/?view=cm&fs=1&to=barryprosser@gmail.com" target="_blank" class="member-btn">'
  print *, '                            <span class="member-name">Barry Prosser</span>'
  print *, '                            <span class="member-role">Guitars / Production / Contact</span>'
  print *, '                        </a>'
  print *, '                    </div>'
  print *, '                </div>'
  print *, '            </div>'
  print *, ''
  print *, '            <div id="more-songs" class="page">'
  print *, '                <div class="header-flex">'
  print *, '                    <h1>The Gallery</h1>'
  print *, '                </div>'
  print *, '                <div class="card">'
  print *, '                    <p style="margin-bottom: 40px; font-size: 1.1rem; font-weight: bold;">Access more content here:</p>'
  print *, '                    <a href="https://www.youtube.com/@resistingthesolace2846" class="big-link" target="_blank">Official Account</a>'
  print *, '                    <a href="https://www.reverbnation.com/resistingthesolace" class="big-link" target="_blank">Official Music Page</a>'
  print *, '                </div>'
  print *, '            </div>'
  print *, ''
  print *, '            <div id="journey" class="page">'
  print *, '                <div class="header-flex">'
  print *, '                    <h1>About Us</h1>'
  print *, '                </div>'
  print *, '                <div class="card">'
  print *, '                    <div class="section-title">The Story</div>'
  print *, '                    <div class="about-text">'
  print *, '                        <p>Resisting the Solace is the creative collaboration of Anniken and Barry Prosser. Born from a shared vision of sonic exploration, the project serves as a vessel for atmospheric soundscapes, cinematic intensity, and raw emotional resonance.</p>'
  print *, '                        <p>The music navigates the delicate balance between shadows and light, blending haunting melodies with powerful production. Each composition is designed to be an immersive experience, inviting the listener into a world where sound tells the story that words often cannot reach.</p>'
  print *, '                        <p>Operating as a self-contained creative unit, Anniken''s evocative vocal delivery meets Barry''s intricate guitar work and production. Together, they continue to push the boundaries of their sound, evolving with every transmission.</p>'
  print *, '                    </div>'
  print *, '                </div>'
  print *, '            </div>'
  print *, ''
  print *, '        </main>'
  print *, '    </div>'
  print *, ''
  print *, '    <script>'
  print *, '        function showPage(pageId) {'
  print *, '            document.querySelectorAll(''.page'').forEach(p => p.classList.remove(''active''));'
  print *, '            document.getElementById(pageId).classList.add(''active'');'
  print *, '            window.scrollTo(0,0);'
  print *, '        }'
  print *, '    </script>'
  print *, ''
  print *, '</body>'
  print *, '</html>'

end program resisting_the_solace
